with enrollments_by_state as (
    select fips as state_id, sum(enrollment) as total_enrollments,
    rank() over (order by sum(enrollment) desc) as rnk
    from ccd_school.us_education_ccd_enrollment_data limit
    where year=2021
    group by fips
)
SELECT 
  CASE state_id
    WHEN 1 THEN 'Alabama'
    WHEN 2 THEN 'Alaska'
    WHEN 3 THEN 'American Samoa'
    WHEN 4 THEN 'Arizona'
    WHEN 5 THEN 'Arkansas'
    WHEN 6 THEN 'California'
    WHEN 7 THEN 'Canal Zone'
    WHEN 8 THEN 'Colorado'
    WHEN 9 THEN 'Connecticut'
    WHEN 10 THEN 'Delaware'
    WHEN 11 THEN 'District of Columbia'
    WHEN 12 THEN 'Florida'
    WHEN 13 THEN 'Georgia'
    WHEN 14 THEN 'Guam'
    WHEN 15 THEN 'Hawaii'
    WHEN 16 THEN 'Idaho'
    WHEN 17 THEN 'Illinois'
    WHEN 18 THEN 'Indiana'
    WHEN 19 THEN 'Iowa'
    WHEN 20 THEN 'Kansas'
    WHEN 21 THEN 'Kentucky'
    WHEN 22 THEN 'Louisiana'
    WHEN 23 THEN 'Maine'
    WHEN 24 THEN 'Maryland'
    WHEN 25 THEN 'Massachusetts'
    WHEN 26 THEN 'Michigan'
    WHEN 27 THEN 'Minnesota'
    WHEN 28 THEN 'Mississippi'
    WHEN 29 THEN 'Missouri'
    WHEN 30 THEN 'Montana'
    WHEN 31 THEN 'Nebraska'
    WHEN 32 THEN 'Nevada'
    WHEN 33 THEN 'New Hampshire'
    WHEN 34 THEN 'New Jersey'
    WHEN 35 THEN 'New Mexico'
    WHEN 36 THEN 'New York'
    WHEN 37 THEN 'North Carolina'
    WHEN 38 THEN 'North Dakota'
    WHEN 39 THEN 'Ohio'
    WHEN 40 THEN 'Oklahoma'
    WHEN 41 THEN 'Oregon'
    WHEN 42 THEN 'Pennsylvania'
    WHEN 43 THEN 'Puerto Rico'
    WHEN 44 THEN 'Rhode Island'
    WHEN 45 THEN 'South Carolina'
    WHEN 46 THEN 'South Dakota'
    WHEN 47 THEN 'Tennessee'
    WHEN 48 THEN 'Texas'
    WHEN 49 THEN 'Utah'
    WHEN 50 THEN 'Vermont'
    WHEN 51 THEN 'Virginia'
    WHEN 52 THEN 'Virgin Islands of the US'
    WHEN 53 THEN 'Washington'
    WHEN 54 THEN 'West Virginia'
    WHEN 55 THEN 'Wisconsin'
    WHEN 56 THEN 'Wyoming'
    WHEN 58 THEN 'Department of Defense Dependent Schools (overseas)'
    WHEN 59 THEN 'Bureau of Indian Education'
    WHEN 60 THEN 'American Samoa'
    WHEN 61 THEN 'Department of Defense Dependent Schools (domestic)'
    WHEN 63 THEN 'Department of Defense Education Activity'
    WHEN 64 THEN 'Federated States of Micronesia'
    WHEN 65 THEN 'Mariana Islands waters (including Guam)'
    WHEN 66 THEN 'Guam'
    WHEN 67 THEN 'Johnston Atoll'
    WHEN 68 THEN 'Marshall Islands'
    WHEN 69 THEN 'Northern Mariana Islands'
    WHEN 70 THEN 'Palau'
    WHEN 71 THEN 'Midway Islands'
    WHEN 72 THEN 'Puerto Rico'
    WHEN 74 THEN 'US Minor Outlying Islands'
    WHEN 75 THEN 'Atlantic coast from North Carolina to Florida, and the coasts of Puerto Rico and Virgin Islands'
    WHEN 76 THEN 'Navassa Island'
    WHEN 78 THEN 'Virgin Islands of the US'
    WHEN 79 THEN 'Wake Island'
    WHEN 81 THEN 'Baker Island'
    WHEN 84 THEN 'Howland Island'
    WHEN 86 THEN 'Jarvis Island'
    WHEN 89 THEN 'Kingman Reef'
    WHEN 95 THEN 'Palmyra Atoll'
    WHEN -1 THEN 'Missing/not reported'
    WHEN -2 THEN 'Not applicable'
    WHEN -3 THEN 'Suppressed data'
    ELSE 'Unknown'
  END AS state,
  total_enrollments
from enrollments_by_state
where rnk <= 10
order by total_enrollments desc
